# Generated by Django 5.0.1 on 2024-02-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_user_message_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='message',
            table='chatapp_message',
        ),
    ]
